#!/usr/bin/env python3

import argparse
import os
from pathlib import Path
import yaml
import pprint as pp
import shutil

import dictcombiner as dc

def print_dict(dict_ : dict):
	printer = pp.PrettyPrinter(indent=4)

	printer.pprint(dict_)

def main():
	parser = argparse.ArgumentParser('Combine subconf files into proper MC configs.')

	parser.add_argument(
		'--confdir',
		dest='confdir',
		metavar='[confdir]',
		help='Directory which contains config files to combine',
		required=True)

	parser.add_argument(
		'--serverdir',
		dest='serverdir',
		metavar='[serverdir]',
		help='Directory of the target server',
		required=True)

	args = parser.parse_args()

	yml_files = ['bukkit.yml', 'spigot.yml', 'paper.yml']
	serverdir = Path(args.serverdir).resolve()
	confdir = Path(args.confdir).resolve()

	if not serverdir.exists():
		raise FileNotFoundError(serverdir)

	if not serverdir.is_dir():
		raise NotADirectoryError(serverdir)

	if not confdir.exists():
		raise FileNotFoundError(confdir)

	if not confdir.is_dir():
		raise NotADirectoryError(confdir)

	for yml_file in yml_files:
		# The original yml
		base_yml = Path(serverdir, yml_file)

		if not base_yml.exists():
			print('INFO: ' + str(base_yml) + ' does not exist, skipping.')

		elements = base_yml.name.split('.')
		original_yml_name = '.'.join(elements[:-1]) + '_original.' + elements[-1]
		original_yml = Path(base_yml.parent, original_yml_name)

		if not original_yml.exists():
			shutil.move(base_yml, original_yml)
		else:
			print('INFO: ' + str(original_yml) + ' already exists, skipping move.')

		with open(original_yml) as file:
			base_yml_data = yaml.safe_load(file)

		# List sub-yml files and sort alphabetically
		sub_yml_dir = Path(confdir, yml_file)
		sub_yml_files = sorted(
			[Path(filename) for filename in sub_yml_dir.iterdir()],
			key=lambda f: f.name)

		sub_confs = []

		for sub_yml_file in sub_yml_files:
			with open(sub_yml_file) as file:
				sub_yml_data = yaml.safe_load(file)
				sub_confs.append(sub_yml_data)

		result_conf = dc.combine_dicts(base_yml_data, sub_confs)

		# Overwriting is ok since we have copied the original
		with open(base_yml, 'w') as file:
			file.write(yaml.dump(result_conf))

		#print_dict(result_conf)



if __name__ == '__main__':
	main()