#!/usr/bin/env python3

import argparse

import mcconf

def main():
	parser = argparse.ArgumentParser('Minecraft server setup')

	parser.add_argument(
		'--serverconf',
		dest='serverconf',
		metavar='[serverconf]',
		help='Path to serverconf.json',
		required=True)
	parser.add_argument(
		'--rolesdir',
		dest='rolesdir',
		metavar='[rolesdir]',
		help='Directory which contains role config files.',
		required=True)
	parser.add_argument(
		'--serverdir',
		dest='serverdir',
		metavar='[serverdir]',
		help='Directory of the target server',
		required=True)
	parser.add_argument(
		'--dry-run',
		help='Activate dry run.',
		action='store_true')

	args = vars(parser.parse_args())

	sc = mcconf.ServerConf(args)
	sc.init_server()
	#sc.generate_initial_state()

if __name__ == '__main__':
	main()
