#!/usr/bin/env python3

import mcconf
import config
import sys

def print_help():
	print('''
pluginconf command [args..]

Commands:

- download resource_name
	Downloads latest version of specified resource name.
	ex: pluginconf download EssentialsX

- update resource_name
	Downloads and updates symlink of latest version of specified resource name.
	ex: pluginconf update EssentialsX

- list
	Lists configured resources (plugins)
	''')

def list_resources(pc : mcconf.PluginConf):
	for key, value in pc.get_resources().items():
		print(key)

if __name__ == '__main__':
	if len(sys.argv) < 2:
		print_help()
		exit()

	pc = mcconf.PluginConf(config.config)

	command = sys.argv[1]

	if command == 'list':
		list_resources(pc)
