#!/usr/bin/env python3

import argparse

import mcconf

def main():
	parser = argparse.ArgumentParser('Minecraft server setup')

	parser.add_argument(
		'--confdir',
		dest='confdir',
		metavar='[confdir]',
		help='Directory which contains server config files.',
		required=True)
	parser.add_argument(
		'--outdir',
		dest='outdir',
		metavar='[outdir]',
		help='Where to put the new server.',
		default='.')
	parser.add_argument(
		'--dry-run',
		help='Activate dry run.',
		action='store_true')

	args = vars(parser.parse_args())

	sc = mcconf.ServerConf(args)
	sc.init_server()
	#sc.generate_initial_state()

if __name__ == '__main__':
	main()
